In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.model_selection import train_test_split, KFold
from sklearn.linear_model import LogisticRegression, Lasso, Ridge
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, classification_report, roc_auc_score

In [3]:
df = pd.read_csv("Iris.csv")
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
print('Number of records:',df.shape[0])
print('Number of columns:',df.shape[1])

Number of records: 150
Number of columns: 6

In [5]:
# filtered_df = df[(df["Species"]=="Iris-setosa")|(df["Species"]=="Iris-versicolor")]LinearRegression
filtered_df = df[df["Species"].isin(["Iris-setosa","Iris-versicolor"])].copy()

In [6]:
print('Number of records:',filtered_df.shape[0])
print('Number of columns:',filtered_df.shape[1])
filtered_df.tail()

Number of records: 100
Number of columns: 6

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
95,96,5.7,3.0,4.2,1.2,Iris-versicolor
96,97,5.7,2.9,4.2,1.3,Iris-versicolor
97,98,6.2,2.9,4.3,1.3,Iris-versicolor
98,99,5.1,2.5,3.0,1.1,Iris-versicolor
99,100,5.7,2.8,4.1,1.3,Iris-versicolor

In [7]:
# print("We are taking Setosa as 1 and versicolor as 0")
# subset = filtered_df[["SepalLengthCm" , "SepalWidthCm", "Species"]]
# print(subset)
filtered_df["Species"]= filtered_df["Species"].map({'Iris-setosa':1, 'Iris-versicolor':0})

In [8]:
print(filtered_df.head(100))

     Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0     1            5.1           3.5            1.4           0.2        1
1     2            4.9           3.0            1.4           0.2        1
2     3            4.7           3.2            1.3           0.2        1
3     4            4.6           3.1            1.5           0.2        1
4     5            5.0           3.6            1.4           0.2        1
..  ...            ...           ...            ...           ...      ...
95   96            5.7           3.0            4.2           1.2        0
96   97            5.7           2.9            4.2           1.3        0
97   98            6.2           2.9            4.3           1.3        0
98   99            5.1           2.5            3.0           1.1        0
99  100            5.7           2.8            4.1           1.3        0

[100 rows x 6 columns]

In [9]:
X = filtered_df [["SepalLengthCm", "SepalWidthCm"]].values
Y = filtered_df ["Species"].values
print(X,Y)

[[5.1 3.5]
 [4.9 3. ]
 [4.7 3.2]
 [4.6 3.1]
 [5.  3.6]
 [5.4 3.9]
 [4.6 3.4]
 [5.  3.4]
 [4.4 2.9]
 [4.9 3.1]
 [5.4 3.7]
 [4.8 3.4]
 [4.8 3. ]
 [4.3 3. ]
 [5.8 4. ]
 [5.7 4.4]
 [5.4 3.9]
 [5.1 3.5]
 [5.7 3.8]
 [5.1 3.8]
 [5.4 3.4]
 [5.1 3.7]
 [4.6 3.6]
 [5.1 3.3]
 [4.8 3.4]
 [5.  3. ]
 [5.  3.4]
 [5.2 3.5]
 [5.2 3.4]
 [4.7 3.2]
 [4.8 3.1]
 [5.4 3.4]
 [5.2 4.1]
 [5.5 4.2]
 [4.9 3.1]
 [5.  3.2]
 [5.5 3.5]
 [4.9 3.1]
 [4.4 3. ]
 [5.1 3.4]
 [5.  3.5]
 [4.5 2.3]
 [4.4 3.2]
 [5.  3.5]
 [5.1 3.8]
 [4.8 3. ]
 [5.1 3.8]
 [4.6 3.2]
 [5.3 3.7]
 [5.  3.3]
 [7.  3.2]
 [6.4 3.2]
 [6.9 3.1]
 [5.5 2.3]
 [6.5 2.8]
 [5.7 2.8]
 [6.3 3.3]
 [4.9 2.4]
 [6.6 2.9]
 [5.2 2.7]
 [5.  2. ]
 [5.9 3. ]
 [6.  2.2]
 [6.1 2.9]
 [5.6 2.9]
 [6.7 3.1]
 [5.6 3. ]
 [5.8 2.7]
 [6.2 2.2]
 [5.6 2.5]
 [5.9 3.2]
 [6.1 2.8]
 [6.3 2.5]
 [6.1 2.8]
 [6.4 2.9]
 [6.6 3. ]
 [6.8 2.8]
 [6.7 3. ]
 [6.  2.9]
 [5.7 2.6]
 [5.5 2.4]
 [5.5 2.4]
 [5.8 2.7]
 [6.  2.7]
 [5.4 3. ]
 [6.  3.4]
 [6.7 3.1]
 [6.3 2.3]
 [5.6 3. ]
 [5.5 2.5]
 [5.5 2.6]
 [6.1 3. ]
 [5.8 2.6]
 [5.  2.3]
 [5.6 2.7]
 [5.7 3. ]
 [5.7 2.9]
 [6.2 2.9]
 [5.1 2.5]
 [5.7 2.8]] [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

In [10]:
scalar = StandardScaler()
X_normalized = scalar.fit_transform(X)

k = 5
kf = KFold(n_splits=k, shuffle = True, random_state = 42)

test_accuracy = []

In [11]:
for fold, (train_index,test_index) in enumerate(kf.split(X_normalized),1):
    print(f"\n--FOLD {fold}--")
    
    X_train,X_test = X_normalized[train_index], X_normalized[test_index]
    Y_train,Y_test = Y[train_index], Y[test_index]
    
    model = LogisticRegression()
    model.fit(X_train,Y_train)
    
    w1,w2 = model.coef_[0]
    b = model.intercept_[0]
    print(f"Learned Parameters: wi: {w1}, w2 : {w2}, b : {b}")
    
    Y_trainPred = model.predict(X_train)
    Y_testPred = model.predict(X_test)
    
    train_acc = accuracy_score(Y_train, Y_trainPred)
    test_acc = accuracy_score(Y_test, Y_testPred)
    test_accuracy.append(test_acc)
    
    print(f"Train_acc: {train_acc}")
    print(f"Test_acc: {test_acc}")
    
    print("\n --- Classification Report---- ")
    print(classification_report(Y_test, Y_testPred))
    
    y_prob= model.predict_proba(X_test)[:,1] 
    auc_value = roc_auc_score(Y_test, y_prob)
    print(f"AUC value : {auc_value:.4f}")
    print("-" *30)

--FOLD 1--
Learned Parameters: wi: -2.5766261916377156, w2 : 2.068681656470436, b : -0.3765089353877849
Train_acc: 1.0
Test_acc: 1.0

 --- Classification Report----
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      1.00      1.00        12

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

AUC value : 1.0000
------------------------------

--FOLD 2--
Learned Parameters: wi: -2.4694170916924256, w2 : 2.1082339071441805, b : -0.1113133533094864
Train_acc: 1.0
Test_acc: 1.0

 --- Classification Report----
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00        11

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

AUC value : 1.0000
------------------------------

--FOLD 3--
Learned Parameters: wi: -2.5137873568144027, w2 : 2.089653117201368, b : -0.35138683629786144
Train_acc: 0.9875
Test_acc: 1.0

 --- Classification Report----
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         6
           1       1.00      1.00      1.00        14

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

AUC value : 1.0000
------------------------------

--FOLD 4--
Learned Parameters: wi: -2.509849738468533, w2 : 2.145435556111183, b : -0.13096550449610472
Train_acc: 1.0
Test_acc: 1.0

 --- Classification Report----
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      1.00      1.00         5

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

AUC value : 1.0000
------------------------------

--FOLD 5--
Learned Parameters: wi: -2.572880488263667, w2 : 2.095657999744364, b : -0.2911305195762763
Train_acc: 1.0
Test_acc: 1.0

 --- Classification Report----
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20

AUC value : 1.0000
------------------------------

In [12]:
print(f"\nAVERAGE ACCURACY : {np.mean(test_accuracy):.4f}")

AVERAGE ACCURACY : 1.0000